sudo: required
services:
  - docker

before_install:
  - docker build -t maciejrataj88/docker-react -f Dockerfile.dev . 

script:
  - docker run maciejrataj88/docker-react npm run test -- --coverage
  

